/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealixRouteImport } from './routes/healix'
import { Route as ConsultationsRouteImport } from './routes/consultations'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealixIndexRouteImport } from './routes/healix.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReferralsNewRouteImport } from './routes/referrals.new'
import { Route as ReferralsIdRouteImport } from './routes/referrals.$id'
import { Route as HealixSettingsRouteImport } from './routes/healix.settings'
import { Route as HealixRecordsRouteImport } from './routes/healix.records'
import { Route as HealixPrescriptionsRouteImport } from './routes/healix.prescriptions'
import { Route as HealixAppointmentsRouteImport } from './routes/healix.appointments'
import { Route as HealixAnalyticsRouteImport } from './routes/healix.analytics'
import { Route as HealixAiRouteImport } from './routes/healix.ai'
import { Route as AppointmentsNewRouteImport } from './routes/appointments.new'
import { Route as HealixPatientsIndexRouteImport } from './routes/healix.patients.index'
import { Route as HealixPatientsIdRouteImport } from './routes/healix.patients.$id'
import { Route as ApiPublicBootstrapRouteImport } from './routes/api/public/bootstrap'
import { Route as ApiHealixTtsRouteImport } from './routes/api/healix/tts'
import { Route as ApiHealixAiRouteImport } from './routes/api/healix/ai'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealixRoute = HealixRouteImport.update({
  id: '/healix',
  path: '/healix',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationsRoute = ConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealixIndexRoute = HealixIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HealixRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsNewRoute = ReferralsNewRouteImport.update({
  id: '/referrals/new',
  path: '/referrals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIdRoute = ReferralsIdRouteImport.update({
  id: '/referrals/$id',
  path: '/referrals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HealixSettingsRoute = HealixSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HealixRoute,
} as any)
const HealixRecordsRoute = HealixRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => HealixRoute,
} as any)
const HealixPrescriptionsRoute = HealixPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => HealixRoute,
} as any)
const HealixAppointmentsRoute = HealixAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => HealixRoute,
} as any)
const HealixAnalyticsRoute = HealixAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HealixRoute,
} as any)
const HealixAiRoute = HealixAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => HealixRoute,
} as any)
const AppointmentsNewRoute = AppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppointmentsRoute,
} as any)
const HealixPatientsIndexRoute = HealixPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => HealixRoute,
} as any)
const HealixPatientsIdRoute = HealixPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => HealixRoute,
} as any)
const ApiPublicBootstrapRoute = ApiPublicBootstrapRouteImport.update({
  id: '/api/public/bootstrap',
  path: '/api/public/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealixTtsRoute = ApiHealixTtsRouteImport.update({
  id: '/api/healix/tts',
  path: '/api/healix/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealixAiRoute = ApiHealixAiRouteImport.update({
  id: '/api/healix/ai',
  path: '/api/healix/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/healix': typeof HealixRouteWithChildren
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/healix/ai': typeof HealixAiRoute
  '/healix/analytics': typeof HealixAnalyticsRoute
  '/healix/appointments': typeof HealixAppointmentsRoute
  '/healix/prescriptions': typeof HealixPrescriptionsRoute
  '/healix/records': typeof HealixRecordsRoute
  '/healix/settings': typeof HealixSettingsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/healix/': typeof HealixIndexRoute
  '/api/healix/ai': typeof ApiHealixAiRoute
  '/api/healix/tts': typeof ApiHealixTtsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/healix/patients/$id': typeof HealixPatientsIdRoute
  '/healix/patients/': typeof HealixPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/healix/ai': typeof HealixAiRoute
  '/healix/analytics': typeof HealixAnalyticsRoute
  '/healix/appointments': typeof HealixAppointmentsRoute
  '/healix/prescriptions': typeof HealixPrescriptionsRoute
  '/healix/records': typeof HealixRecordsRoute
  '/healix/settings': typeof HealixSettingsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/admin': typeof AdminIndexRoute
  '/healix': typeof HealixIndexRoute
  '/api/healix/ai': typeof ApiHealixAiRoute
  '/api/healix/tts': typeof ApiHealixTtsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/healix/patients/$id': typeof HealixPatientsIdRoute
  '/healix/patients': typeof HealixPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/consultations': typeof ConsultationsRoute
  '/healix': typeof HealixRouteWithChildren
  '/help': typeof HelpRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/masters': typeof MastersRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/healix/ai': typeof HealixAiRoute
  '/healix/analytics': typeof HealixAnalyticsRoute
  '/healix/appointments': typeof HealixAppointmentsRoute
  '/healix/prescriptions': typeof HealixPrescriptionsRoute
  '/healix/records': typeof HealixRecordsRoute
  '/healix/settings': typeof HealixSettingsRoute
  '/referrals/$id': typeof ReferralsIdRoute
  '/referrals/new': typeof ReferralsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/healix/': typeof HealixIndexRoute
  '/api/healix/ai': typeof ApiHealixAiRoute
  '/api/healix/tts': typeof ApiHealixTtsRoute
  '/api/public/bootstrap': typeof ApiPublicBootstrapRoute
  '/healix/patients/$id': typeof HealixPatientsIdRoute
  '/healix/patients/': typeof HealixPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/consultations'
    | '/healix'
    | '/help'
    | '/hospitals'
    | '/login'
    | '/masters'
    | '/patients'
    | '/settings'
    | '/appointments/new'
    | '/healix/ai'
    | '/healix/analytics'
    | '/healix/appointments'
    | '/healix/prescriptions'
    | '/healix/records'
    | '/healix/settings'
    | '/referrals/$id'
    | '/referrals/new'
    | '/admin/'
    | '/healix/'
    | '/api/healix/ai'
    | '/api/healix/tts'
    | '/api/public/bootstrap'
    | '/healix/patients/$id'
    | '/healix/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/consultations'
    | '/help'
    | '/hospitals'
    | '/login'
    | '/masters'
    | '/patients'
    | '/settings'
    | '/appointments/new'
    | '/healix/ai'
    | '/healix/analytics'
    | '/healix/appointments'
    | '/healix/prescriptions'
    | '/healix/records'
    | '/healix/settings'
    | '/referrals/$id'
    | '/referrals/new'
    | '/admin'
    | '/healix'
    | '/api/healix/ai'
    | '/api/healix/tts'
    | '/api/public/bootstrap'
    | '/healix/patients/$id'
    | '/healix/patients'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/consultations'
    | '/healix'
    | '/help'
    | '/hospitals'
    | '/login'
    | '/masters'
    | '/patients'
    | '/settings'
    | '/appointments/new'
    | '/healix/ai'
    | '/healix/analytics'
    | '/healix/appointments'
    | '/healix/prescriptions'
    | '/healix/records'
    | '/healix/settings'
    | '/referrals/$id'
    | '/referrals/new'
    | '/admin/'
    | '/healix/'
    | '/api/healix/ai'
    | '/api/healix/tts'
    | '/api/public/bootstrap'
    | '/healix/patients/$id'
    | '/healix/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  ConsultationsRoute: typeof ConsultationsRoute
  HealixRoute: typeof HealixRouteWithChildren
  HelpRoute: typeof HelpRoute
  HospitalsRoute: typeof HospitalsRoute
  LoginRoute: typeof LoginRoute
  MastersRoute: typeof MastersRoute
  PatientsRoute: typeof PatientsRoute
  SettingsRoute: typeof SettingsRoute
  ReferralsIdRoute: typeof ReferralsIdRoute
  ReferralsNewRoute: typeof ReferralsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiHealixAiRoute: typeof ApiHealixAiRoute
  ApiHealixTtsRoute: typeof ApiHealixTtsRoute
  ApiPublicBootstrapRoute: typeof ApiPublicBootstrapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healix': {
      id: '/healix'
      path: '/healix'
      fullPath: '/healix'
      preLoaderRoute: typeof HealixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultations': {
      id: '/consultations'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof ConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healix/': {
      id: '/healix/'
      path: '/'
      fullPath: '/healix/'
      preLoaderRoute: typeof HealixIndexRouteImport
      parentRoute: typeof HealixRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/new': {
      id: '/referrals/new'
      path: '/referrals/new'
      fullPath: '/referrals/new'
      preLoaderRoute: typeof ReferralsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/$id': {
      id: '/referrals/$id'
      path: '/referrals/$id'
      fullPath: '/referrals/$id'
      preLoaderRoute: typeof ReferralsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healix/settings': {
      id: '/healix/settings'
      path: '/settings'
      fullPath: '/healix/settings'
      preLoaderRoute: typeof HealixSettingsRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/records': {
      id: '/healix/records'
      path: '/records'
      fullPath: '/healix/records'
      preLoaderRoute: typeof HealixRecordsRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/prescriptions': {
      id: '/healix/prescriptions'
      path: '/prescriptions'
      fullPath: '/healix/prescriptions'
      preLoaderRoute: typeof HealixPrescriptionsRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/appointments': {
      id: '/healix/appointments'
      path: '/appointments'
      fullPath: '/healix/appointments'
      preLoaderRoute: typeof HealixAppointmentsRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/analytics': {
      id: '/healix/analytics'
      path: '/analytics'
      fullPath: '/healix/analytics'
      preLoaderRoute: typeof HealixAnalyticsRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/ai': {
      id: '/healix/ai'
      path: '/ai'
      fullPath: '/healix/ai'
      preLoaderRoute: typeof HealixAiRouteImport
      parentRoute: typeof HealixRoute
    }
    '/appointments/new': {
      id: '/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppointmentsNewRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/healix/patients/': {
      id: '/healix/patients/'
      path: '/patients'
      fullPath: '/healix/patients/'
      preLoaderRoute: typeof HealixPatientsIndexRouteImport
      parentRoute: typeof HealixRoute
    }
    '/healix/patients/$id': {
      id: '/healix/patients/$id'
      path: '/patients/$id'
      fullPath: '/healix/patients/$id'
      preLoaderRoute: typeof HealixPatientsIdRouteImport
      parentRoute: typeof HealixRoute
    }
    '/api/public/bootstrap': {
      id: '/api/public/bootstrap'
      path: '/api/public/bootstrap'
      fullPath: '/api/public/bootstrap'
      preLoaderRoute: typeof ApiPublicBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healix/tts': {
      id: '/api/healix/tts'
      path: '/api/healix/tts'
      fullPath: '/api/healix/tts'
      preLoaderRoute: typeof ApiHealixTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/healix/ai': {
      id: '/api/healix/ai'
      path: '/api/healix/ai'
      fullPath: '/api/healix/ai'
      preLoaderRoute: typeof ApiHealixAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsNewRoute: typeof AppointmentsNewRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsNewRoute: AppointmentsNewRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface HealixRouteChildren {
  HealixAiRoute: typeof HealixAiRoute
  HealixAnalyticsRoute: typeof HealixAnalyticsRoute
  HealixAppointmentsRoute: typeof HealixAppointmentsRoute
  HealixPrescriptionsRoute: typeof HealixPrescriptionsRoute
  HealixRecordsRoute: typeof HealixRecordsRoute
  HealixSettingsRoute: typeof HealixSettingsRoute
  HealixIndexRoute: typeof HealixIndexRoute
  HealixPatientsIdRoute: typeof HealixPatientsIdRoute
  HealixPatientsIndexRoute: typeof HealixPatientsIndexRoute
}

const HealixRouteChildren: HealixRouteChildren = {
  HealixAiRoute: HealixAiRoute,
  HealixAnalyticsRoute: HealixAnalyticsRoute,
  HealixAppointmentsRoute: HealixAppointmentsRoute,
  HealixPrescriptionsRoute: HealixPrescriptionsRoute,
  HealixRecordsRoute: HealixRecordsRoute,
  HealixSettingsRoute: HealixSettingsRoute,
  HealixIndexRoute: HealixIndexRoute,
  HealixPatientsIdRoute: HealixPatientsIdRoute,
  HealixPatientsIndexRoute: HealixPatientsIndexRoute,
}

const HealixRouteWithChildren =
  HealixRoute._addFileChildren(HealixRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  ConsultationsRoute: ConsultationsRoute,
  HealixRoute: HealixRouteWithChildren,
  HelpRoute: HelpRoute,
  HospitalsRoute: HospitalsRoute,
  LoginRoute: LoginRoute,
  MastersRoute: MastersRoute,
  PatientsRoute: PatientsRoute,
  SettingsRoute: SettingsRoute,
  ReferralsIdRoute: ReferralsIdRoute,
  ReferralsNewRoute: ReferralsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiHealixAiRoute: ApiHealixAiRoute,
  ApiHealixTtsRoute: ApiHealixTtsRoute,
  ApiPublicBootstrapRoute: ApiPublicBootstrapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
